version: "3.1"
services:
  backend:
    build: backend
    command: npm start
    depends_on:
    - mongodb_container
    ports:
    - 5000:5000
    environment:
      MONGODB_URI: mongodb://mongodb_container:27017/yolomy?retryWrites=true&w=majority

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27020:27017
    volumes:
      - mongodb_data_container:/data/db

  client:
    container_name: ecommerceportal
    build:
        context: client
        dockerfile: Dockerfile.prod
    #command: npm start
    ports:
    - 3333:80

    depends_on:
    - backend
   
volumes:
    mongodb_data_container:

